default_platform(:ios)

platform :ios do
  desc "Build and upload a QA build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["App_Store_Connect"],
      is_key_content_base64: true
    )

    increment_build_number(
      xcodeproj: "Landmarks.xcodeproj",
      build_number: ENV["CIRCLE_BUILD_NUM"]
    )

    build_app(
      project: "Landmarks.xcodeproj",
      scheme: "Landmarks",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates " \
              "-authenticationKeyPath \"#{api_key[:key_filepath]}\" " \
              "-authenticationKeyID \"#{api_key[:key_id]}\" " \
              "-authenticationKeyIssuerID \"#{api_key[:issuer_id]}\""
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
